defaults :
  - modulus_default
  - arch:
      - fully_connected
#      - layer_size: 20
#      - nr_layers: 6
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: False
cuda_graphs: True
cuda_graph_warmup: 1
#debug: True
scheduler:
  decay_rate: 0.95
  decay_steps: 2000


#scheduler:
#  initial_learning_rate: 0.02
#  gamma: 0.25
#  step: 1000

#  exponential_lr: 0.01
#  decay_rate: 0.95
#  decay_steps: 1000

training:
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps : 10000

batch_size:
  TopWall: 7200
  BottomWall: 7200
  LeftWall: 7200
  RightWall: 7200
  Interior: 7200 #43200
  wake1_above: 1200
  wake2_above: 1200
  wake3_above: 1200
  wake1_below: 1200
  wake2_below: 1200
  wake3_below: 1200
  obstacle_above: 1200  # This value used for calculation of points in other domains (Top, Left, ...).
  obstacle_below: 1200
#  Inference_int_pts: 10000

run_mode: 'train'

custom:
  obstacle_length: 0.10  # flat plate length
  unscaled_domain_height: 6
  unscaled_domain_width: 6
  dx : 0.0015  # hardcoded, please follow below lines
  dy : 0.0015  # hardcoded, please follow below lines
  # dx: 0.015 * cfg.custom.obstacle_length   # Is the distance between the main point and the constructed points across the x-axis.
  # dy: 0.015 * cfg.custom.obstacle_length  # Is the distance between the main point and the constructed point across the y-axis.
  batch_size_temp: 7     # used to calculate alpha
  neigh_point_kd_tree: 7     # number of neighbours from a point in KD-tree
  band_range_y_belt: [-0.015, 0.015]  # This is the range of y values of the belt.
  band_range_y: [-0.06, 0.06]  # This is the range of y values of the band.
  x_range_sub_pc: 0.3  # sub point cloud x range
  y_range_sub_pc: 0.6    # sub-point cloud y range
  free_stream_velocity: 10